<template>
  <div class="pl-12">Passkey Seed</div>
  <v-container class="pb-6 pt-0">
    <v-card-text class="pl-12">
      <div class="pb-3">
        You may need to connect to your device up to
        <b>3</b>
        times:
      </div>
      <ol class="pl-8">
        <li>Check if passkey already exists.</li>
        <li>Register new passkey on device.</li>
        <li>Request entropy from passkey.</li>
      </ol>
    </v-card-text>
    <v-row class="text-center">
      <v-col>
        <v-btn text="Get Started" @click="restoreOrRegister()" />
      </v-col>
    </v-row>
  </v-container>
</template>

<script lang="ts" setup>
import Seed from "@/services/Seed";

const emit = defineEmits(["close", "seed"]);

const store = useAppStore();

async function restoreOrRegister() {
  try {
    const resp = await Seed.getPasskeySeed();
    const seedId = await Seed.storePasskeyCred(resp.credentialId);
    emit("seed", seedId, resp.seed);
    return;
  } catch (err: any) {
    console.error(err);
    // Registration is only offered when there is nothing to restore from, or
    // when what was found cannot derive a seed. WebAuthn reports a cancelled
    // prompt and a device with no passkey the same way, so "aborted" has to
    // fall through, but any other failure stops here instead of pushing the
    // user towards a second registration.
    if (err.code !== "aborted" && err.code !== "prf") {
      store.setSnackbar(err.message, "error");
      return;
    }
  }
  if (
    !confirm(`WARNING: READ CAREFULLY!

If you have already registered a passkey for this site, registering another one gives you a second, unrelated seed. It will not recover the accounts generated by the existing passkey, and some devices only keep one passkey per site. If you are not sure, cancel and start over.

Are you sure you want to register a new passkey?`)
  ) {
    store.snackbar.display = false;
    return;
  }

  try {
    const credentialId = await Seed.registerPasskey();
    const { seed } = await Seed.getPasskeySeed(credentialId);
    const seedId = await Seed.storePasskeyCred(credentialId);
    emit("seed", seedId, seed);
  } catch (err: any) {
    console.error(err);
    store.setSnackbar(err.message, "error");
  }
}
</script>
