<template>
  <div class="pl-12">Passkey Seed</div>
  <v-container class="pb-6">
    <v-card-text class="pl-12 pt-0">
      Supported Devices
      <ul class="pl-8">
        <li>Android 14</li>
        <li>YubiKey</li>
      </ul>
    </v-card-text>
    <v-card-text class="pl-12">
      <div class="pb-3">
        You may need to connect to your device up to
        <b>3</b>
        times:
      </div>
      <ol class="pl-8">
        <li>Check if passkey already exists.</li>
        <li>Register new passkey on device.</li>
        <li>Request entropy from passkey.</li>
      </ol>
    </v-card-text>
    <v-row class="text-center">
      <v-col>
        <v-btn text="Get Started" @click="restoreOrRegister()" />
      </v-col>
    </v-row>
  </v-container>
</template>

<script lang="ts" setup>
import Seed from "@/services/Seed";

const emit = defineEmits(["close", "seed"]);

const store = useAppStore();

async function restoreOrRegister() {
  try {
    const resp = await Seed.getPasskeySeed();
    const seedId = await Seed.storePasskeyCred(resp.credentialId);
    emit("seed", seedId, resp.seed);
  } catch (err) {
    console.error(err);
    if (
      !confirm(`WARNING: READ CAREFULLY!

If you have already registered a passkey for this site and you choose to register another, your device may silently overwrite the existing passkey causing loss of access to any accounts generated by it. If you are not sure, cancel and start over.

Are you sure you want to register a new passkey?`)
    )
      return;
    try {
      const name = "wallet@lute.app";
      const credential = await navigator.credentials.create({
        publicKey: {
          authenticatorSelection: {
            residentKey: "required",
          },
          challenge: new Uint8Array(32),
          pubKeyCredParams: [
            { alg: -7, type: "public-key" },
            { alg: -8, type: "public-key" },
            { alg: -257, type: "public-key" },
          ],
          rp: { name: "Lute" },
          user: {
            id: new Uint8Array(32),
            name,
            displayName: name,
          },
        },
      });
      if (!credential) throw Error("Invalid Credential");
      const credentialId = credential.id;
      const seedId = await Seed.storePasskeyCred(credentialId);
      const { seed } = await Seed.getPasskeySeed(credentialId);
      emit("seed", seedId, seed);
    } catch (err: any) {
      console.error(err);
      store.setSnackbar(err.message, "error");
    }
  }
}
</script>
